name: PebbleShop
version: ${project.version}
main: me.deadlight.ezchestshop.EzChestShop
api-version: 1.16
folia-supported: true
depend:
  - PebbleCore
softdepend:
  - WildChests
  - WorldGuard
  - Multiverse-Core # preventing null worlds
  - CMI
  - PlaceholderAPI
  - Towny
authors: [Gluckz, ItzAmirreza, ElitoGame]
description: Pebble Quest player chest shop economy system
commands:
  ecs:
    description: Create, remove, and manage PebbleShop market stalls
    aliases:
      - pshop
      - ps
      - pebbleshop
      - pebblestore
      - cs
      - cshop
      - chestshop
  ecsadmin:
    description: PebbleShop admin moderation commands
    aliases:
      - pshopadmin
      - psadmin
      - pebbleadminshop
      - pebblemarketadmin
  checkprofits:
    description: Check your PebbleShop profit report
    aliases:
      - cp
      - profits
      - shopprofits
